//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Menu_core
    {
        public const string BundleName = "menu_core";
        public const string MAINMENUUNLIT = "MainMenuUnlit";
        public const string 主菜单 = "主菜单";
        public const string MAINMENUPANEL = "MainMenuPanel";
    }
    public class Menu_fx
    {
        public const string BundleName = "menu_fx";
        public const string MENU = "menu";
    }
    public class Unifiedraytracing
    {
        public const string BundleName = "unifiedraytracing";
        public const string GEOMETRYPOOLKERNELS = "GeometryPoolKernels";
        public const string COPYBUFFER = "CopyBuffer";
        public const string BIT_HISTOGRAM = "bit_histogram";
        public const string BLOCK_REDUCE_PART = "block_reduce_part";
        public const string BLOCK_SCAN = "block_scan";
        public const string BUILD_HLBVH = "build_hlbvh";
        public const string COPYPOSITIONS = "CopyPositions";
        public const string RESTRUCTURE_BVH = "restructure_bvh";
        public const string SCATTER = "scatter";
    }
}
